accumulate_grad_batches: 1
audio_sample_rate: 44100
binarization_args:
  merge_rest: true
  merge_slur: false
  num_workers: 8
  round_midi: false
  shuffle: true
  skip_glide: true
  slur_tolerance: 0.5
binarizer_cls: preprocessing.MIDIExtractionBinarizer
binary_data_dir: data/some_ds_spk5_continuous
clip_grad_norm: 1
dataloader_prefetch_factor: 2
ds_workers: 4
finetune_ckpt_path: null
finetune_enabled: false
finetune_ignored_params: []
finetune_strict_shapes: true
fmax: 8000
fmin: 40
freezing_enabled: false
frozen_params: []
hop_size: 512
key_shift_factor: 8
key_shift_range:
- -12
- 12
log_interval: 100
lr_scheduler_args:
  min_lr: 1.0e-05
  scheduler_cls: lr_scheduler.scheduler.WarmupLR
  warmup_steps: 5000
max_batch_frames: 80000
max_batch_size: 20
max_updates: 100000
max_val_batch_frames: 10000
max_val_batch_size: 1
midi_extractor_args:
  attention_drop: 0.1
  attention_heads: 8
  attention_heads_dim: 64
  conv_drop: 0.1
  dim: 512
  ffn_latent_drop: 0.1
  ffn_out_drop: 0.1
  kernel_size: 31
  lay: 8
  use_lay_skip: true
midi_max: 127
midi_min: 0
midi_num_bins: 128
midi_prob_deviation: 1.0
model_cls: modules.model.Gmidi_conform.midi_conforms
nccl_p2p: true
num_ckpt_keep: 5
num_sanity_val_steps: 1
num_valid_plots: 50
optimizer_args:
  beta1: 0.9
  beta2: 0.98
  lr: 0.0001
  optimizer_cls: torch.optim.AdamW
  weight_decay: 0
pe: rmvpe
pe_ckpt: pretrained/rmvpe/model.pt
permanent_ckpt_interval: 8000
permanent_ckpt_start: 60000
pl_trainer_accelerator: auto
pl_trainer_devices: auto
pl_trainer_num_nodes: 1
pl_trainer_precision: bf16-mixed
pl_trainer_strategy:
  find_unused_parameters: false
  name: auto
  process_group_backend: nccl
raw_data_dir:
- data/junninghua1
- data/junninghua2
- data/thea
- data/qixuan
- data/zhibin
- data/luoxi
rest_threshold: 0.1
sampler_frame_count_grid: 6
seed: 114514
sort_by_len: true
task_cls: training.MIDIExtractionTask
test_prefixes:
- 0:FengYingYue_002
- 0:JuanZhuLian_013
- 0:QinShi_013
- 0:WuJiYa_002
- 0:YuanCangTianBianLeXin_000
- 1:GuanShanJiu_006
- 1:MuYunQi_010
- 1:ShiErFengHuaJian_004
- 1:Xia_008
- 1:YiXiuYun_013
- 2:GaoBieQu_003
- 2:GuYongZhe_002
- 2:JinLiChao_006
- 2:LiuGuangJi_012
- 2:PoXiaoJiangZhi_004
- 2:SanCunTianTang_002
- 2:TaoMaGan_006
- 2:YanHuo_012
- 2:YeHuo_014
- 2:YueErYao_006
- 3:DongWuSenLin_021
- 3:HaoXiangAiZheGeShiJieA_001
- 3:HuaPi_001
- 3:LianBeiTaiDouBuShi_014
- 3:MingTianNiHao_028
- 3:SaYe2_000
- 3:ShiXinDongA_014
- 3:WanYouYinLi_011
- 3:XiaoMaoPaoPao_018
- 3:ZhuiLuoXingKong2_014
- 4:000_buweixia_8
- 4:020_tashanhe_10
- 4:027_yanwuxie_2
- 4:008_jianghumeng_7
- 4:010_keketuohaidemuyangren_1
- 4:032_qingqinghebiancao_1
- 4:034_naxienian_14
- 4:035_yingtaohong_2
- 4:037_daojiangxing_3
- 4:011_liangliang_9
- 5:013_deng_wav_9
- 5:020_feiyunzhixia_wav_2
- 5:035_niyidingyaoxinfu_wav_1
- 5:045_wenrou_wav_2
- 5:048_xiangwozheyangderen_wav_4
- 5:060_ayimo_wav_9
- 5:063_chezhan_wav_3
- 5:065_dangwoxiangnideshihou_wav_1
- 5:067_fuqinrijilidesanwenshi_wav_11
- 5:068_geigei_wav_9
train_set_name: train
units_dim: 80
units_encoder: mel
units_encoder_ckpt: pretrained/contentvec/checkpoint_best_legacy_500.pt
use_bound_loss: true
use_midi_loss: true
val_check_interval: 5000
valid_set_name: valid
win_size: 2048
